### ISSUE TITLE
index was outside the bound of array 

### ISSUE THREAD

**Issue by aymansa** [XamarinUniversity/XAM150#2]

**Comment by aymansa** [comment]
when i download  exercise and run it on visual studio  community  and  run  the app on xamarin live player it appear visualization error  index was outside the bound of array

**Comment by patridge** [comment]
I'll take a look at it. There are definitely some limitations of the code that can execute in the Xamarin Live Player. This course's exercises may run into that situation.

**Comment by patridge** [comment]
Closing. This is going to be a limitation of Xamarin Live Player. If those restrictions are eased in the future, we can start to encourage its use in this course.

**Comment by sdwhitney** [comment]
It would help if this was listed as a restriction in the course content.  I tried to do the same thing, and it was very frustrating to get this obscure error.  Thanks!

**Comment by markjulmar** [comment]
Hi @sdwhitney  --

Just a as a note moving forward in your learning, we do not recommend using Live Player for any of our courses. Almost all of them are too complex to run in that simplified environment.

Live Player is really intended for the File > New, first screen experience for brand new users. Once you move past that and add any code to the project you will need to move to a real simulator or device. The Visual Studio team will be making this more clear in future releases of VS as the messaging is a bit soft right now.

Sorry for the confusion!

**Comment by sdwhitney** [comment]
Thank you very much for this info, Mark.  I'll use an Android emulator
going forward.

Best regards,

Scott Whitney
