### ISSUE TITLE
API content response doesn't return created book when call POST request

### ISSUE THREAD

**Issue by maugerc** [XamarinUniversity/XAM150#4]
## What are you seeing?
Bad Content in response from REST API for XAML150 course when i trying to POST my new book, I receive from API a JSON without my created book.
Response content :
```
{
    "version": {
        "major": 1,
        "minor": 1,
        "build": -1,
        "revision": -1,
        "majorRevision": -1,
        "minorRevision": -1
    },
    "content": null,
    "statusCode": 201,
    "reasonPhrase": "Created",
    "headers": [],
    "requestMessage": null,
    "isSuccessStatusCode": true
}
```

## What is expected?
A created book object serialized in JSON.
Exemple:
```
{
    "isbn": "5783674481",
    "title": "Clean Code",
    "authors": [
        "Robert Martin"
    ],
    "publishDate": "2019-03-28T00:00:00",
    "genre": "Productivity",
    "href": "api/books/5783674481"
}
```

## What steps did you take to see this?
POST request send with Postman:
```
POST /api/books HTTP/1.1
Host: xam150.azurewebsites.net
Authorization: bfa6a2f2-03b0-4baf-8d47-596d4fd33bbb
Content-Type: application/json
: 
cache-control: no-cache
Postman-Token: 73156c78-7486-4b3a-a2b5-adbdabba4c9b
{
    "isbn": "",
    "title": "Clean Code",
    "authors": [
        "Robert Martin"
    ],
    "publishDate": "2019-03-28T00:00:00",
    "genre": "Productivity"
}------WebKitFormBoundary7MA4YWxkTrZu0gW--
```

## Have any logged output/error messages that might help?
No error, the HTTP status code is OK.

### What operating system are you using? Windows? macOS?
Windows 10

### What version of Visual Studio are you using?
VS 2017 15.9.10

**Comment by patridge** [comment]
I can confirm this on my machine with Postman. I'll see if I can find out why that is happening now.

**Comment by patridge** [comment]
@maugerc First off, thank you for filing this issue. It is definitely not matching up with the instructions.

I checked what the server code is doing. It isn't returning the new book object at all, it's returning the  status code as the JSON body. For what would be "proper" for a REST API, it should instead set the header to **201 CREATED** and returning a location URI for the retrieving the newly created object. So, while it's not behaving properly for REST standards, this is the way I expect the incorrect code to behave.

I'll update the instructions to eliminate the confusion for now, but we'll try to get the server being more REST-proper next.

**Comment by patridge** [comment]
Instructions updated and deploying soon.

**Comment by maugerc** [comment]
@patridge yes I agree with you, but in my memories the created object must be return with location url. I found on mozilla documentation (https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/201)

> the new resource is returned in the body of the message, its location being either the URL of the request, or the content of the Location header.

but thank for your reply and has solved this ambiguity
